Repository F5Networks/neutron-lbaas-dashboard, pull requests merged in 2018-09, with the labels that each got.

#25 rebase stable/rocky branch 2018-09-06T04:00:34+00:00
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
  neutron_lbaas_dashboard/locale/ko_KR/LC_MESSAGES/djangojs.po
Labels: rebase

#27 Enable Travis CI in Mitaka branch
  .gitignore
  .travis.yml
  neutron_lbaas_dashboard/karma.conf.js
  neutron_lbaas_dashboard/post_install.sh
  neutron_lbaas_dashboard/static/app/core/openstack-service-api/barbican.service.spec.js
  neutron_lbaas_dashboard/static/app/core/openstack-service-api/lbaasv2.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/loadbalancers/loadbalancers.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/pools/detail.controller.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/model.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/model.service.spec.js
  package.json
  test-requirements.txt
Labels: enhancement

#33 rebase master branch 2018-09-16T04:00:42+00:00
  neutron_lbaas_dashboard/locale/de/LC_MESSAGES/djangojs.po
  neutron_lbaas_dashboard/locale/id/LC_MESSAGES/djangojs.po
  neutron_lbaas_dashboard/locale/ja/LC_MESSAGES/djangojs.po
  neutron_lbaas_dashboard/locale/ko_KR/LC_MESSAGES/djangojs.po
Labels: rebase

#36 rebase stable/queens branch 2018-09-16T04:01:00+00:00
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: rebase

#34 rebase stable/pike branch 2018-09-16T04:00:43+00:00
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: rebase

#35 rebase stable/ocata branch 2018-09-16T04:00:46+00:00
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: rebase

#37 Cannot update ssl certificate when update listener
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: community bug

#38 Cannot update ssl certificate when update listener
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: community bug

#19 Enable Travis CI
  .travis.yml
Labels: enhancement

#21 Enable Travis CI in rocky branch
  .travis.yml
Labels: enhancement

#22 Enable Travis CI in queens branch
  .travis.yml
Labels: enhancement

#23 Enable Travis CI in Pike branch
  .travis.yml
Labels: enhancement

#24 Enable Travis CI in Ocata branch
  .travis.yml
  tools/tox_install.sh
Labels: enhancement

#26 Enable Travis CI in Newton branch
  .gitignore
  .travis.yml
  neutron_lbaas_dashboard/karma.conf.js
  neutron_lbaas_dashboard/post_install.sh
  neutron_lbaas_dashboard/static/app/core/openstack-service-api/barbican.service.spec.js
  neutron_lbaas_dashboard/static/app/core/openstack-service-api/lbaasv2.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/loadbalancers/loadbalancers.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/pools/detail.controller.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/model.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/model.service.spec.js
  package.json
  test-requirements.txt
Labels: enhancement

#32 Complete the function of ssl-offloading certificate creation.
  neutron_lbaas_dashboard/api/rest/barbican.py
  neutron_lbaas_dashboard/karma.conf.js
  neutron_lbaas_dashboard/static/app/core/openstack-service-api/barbican.service.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/certificates/certificates.controller.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/certificates/certificates.controller.spec.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/certificates/certificates.html
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/certificates/create-certificate.controller.js
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/certificates/create-certificate.html
  neutron_lbaas_dashboard/static/dashboard/project/lbaasv2/workflow/model.service.js
Labels: enhancement

#40 sni_container_refs needed if we want to use sni
  neutron_lbaas_dashboard/api/rest/lbaasv2.py
Labels: community bug

#44 Fix the travis CI issue: pip repo upgrades the XStatic-JQuery version…
  test-requirements.txt
Labels: bug

#48 rebase master branch 2018-09-30T04:00:24+00:00
  .zuul.yaml
  neutron_lbaas_dashboard/locale/ko_KR/LC_MESSAGES/djangojs.po
Labels: rebase
